[package]
name = "station-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync", "macros", "rt"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = "0.1"
tokio-stream = { version = "0.1", features = ["sync"] }
